services:
  mail:
    # Our mail server's hostname. For important information on choosing this
    # value, please see the README.
    hostname: mail.example.com

    # Build the image from this directory.
    build: .

    # If the container stops, restart it automatically.
    restart: always

    ports:
      # Postfix listens to these ports, as defined in `etc/postfix/master.cf`:

      # SMTP submission through implicit TLS.
      - "465:465"
      # SMTP submission with STARTTLS.
      - "587:587"

    # Runs Tini as the container's init process. For more information, see:
    # https://github.com/krallin/tini#why-tini
    init: true

    volumes:
      # Persist Postfix's queue directory so queued mail isn't lost on restart.
      - postfix-queue:/var/spool/postfix

      # Persist our Dovecot database.
      - dovecot-db:/etc/auth

      # Persist our DKIM private keys.
      - dkim-keys:/home/dkim/keys

      # Persist `dehydrated`'s base directory with our TLS certificates and
      # related files.
      - dehydrated-basedir:/home/acme/dehydrated

    secrets:
      # The account email to give to Let's Encrypt, so that it can send us
      # important notifications like expiring TLS certificates that failed to
      # renew.
      - source: ACME_ACCOUNT_EMAIL
        # Let the `acme` user created in our `usr/local/bin/prebuild` script
        # access this secret's value.
        uid: "10001"
        mode: 0400

      # The Cloudflare API token for our domain, so the server can set our DNS
      # records automatically when needed.
      - source: CF_API_TOKEN
        # Let users in the `cf-api-token` group created in our
        # `usr/local/bin/prebuild` script access this secret's value.
        gid: "20001"
        mode: 0440

volumes:
  postfix-queue:
  dovecot-db:
  dkim-keys:
  dehydrated-basedir:

# All secrets should be loaded from environment variables. You can load the
# environment variables from your `.env` file by writing `source .env && `
# before the `docker compose up` command when starting this container.
secrets:
  ACME_ACCOUNT_EMAIL:
    environment: ACME_ACCOUNT_EMAIL
  CF_API_TOKEN:
    environment: CF_API_TOKEN
