services:
  mail:
    # Our mail server's hostname. For important information on choosing this
    # value, please see the README.
    hostname: mail.example.com

    # Build the image from this directory.
    build: .

    # If the container stops, restart it automatically.
    restart: always

    ports:
      # Postfix listens to these ports, as defined in `etc/postfix/master.cf`:

      # SMTP submission through implicit TLS.
      - "465:465"
      # SMTP submission with STARTTLS.
      - "587:587"

    volumes:
      # Persist Postfix's queue directory so queued mail isn't lost on restart.
      - postfix-queue:/var/spool/postfix

      # Persist our Dovecot database.
      - dovecot-db:/etc/dovecot/db

      # Persist our DKIM private keys.
      - dkim-db:/var/db/dkim

volumes:
  postfix-queue:
  dovecot-db:
  dkim-db:
