services:
  mail:
    restart: always
    hostname: mail.example.com
    build: .

    ports:
      # Postfix listens to these ports, as defined in `etc/postfix/master.cf`:

      # SMTP submission through implicit TLS.
      - "465:465"
      # SMTP submission with STARTTLS.
      - "587:587"

    volumes:
      # Persist Postfix's queue directory so queued mail isn't lost on restart.
      - postfix-queue:/var/spool/postfix

volumes:
  postfix-queue:
